(define (pascal row col)
  (cond ((> col row) (error "invalid value"))
        ((or (= col 0) (= row col)) 1)
        (else (+ (pascal (- row 1) col)
                 (pascal (- row 1) (- col 1))))))
